package org.bamburov.ta.rule;

public enum BollingerState {
    DEFAULT,
    HIGH_ABOVE_THE_UPPER_LINE,
    RECENTLY_BACK_TO_RANGE_FROM_HIGH,
    BETWEEN_UPPER_AND_MIDDLE_LINES,
    CROSSED_MIDDLE,
    BETWEEN_MIDDLE_AND_LOWER_LINES,
    RECENTLY_BACK_TO_RANGE_FROM_LOW,
    LOW_BELOW_THE_LOWER_LINE
}
